let selectedDoc="Other",files=[],lang="en",requestNo=1025;
const $=id=>document.getElementById(id);
const T={
pa:{title:"ਪ੍ਰਿੰਟ ਸੇਵਾ",doc:"ਦਸਤਾਵੇਜ਼",upload:"ਫਾਈਲ ਅੱਪਲੋਡ ਅਤੇ ਪ੍ਰੀਵਿਊ",settings:"ਪ੍ਰਿੰਟ ਸੈਟਿੰਗ",type:"ਪ੍ਰਿੰਟ ਕਿਸਮ",layout:"ਲੇਆਉਟ",copies:"ਕਾਪੀਆਂ",sheets:"A4 ਸ਼ੀਟਾਂ",total:"ਕੁੱਲ",online:"ਆਨਲਾਈਨ",cash:"ਨਕਦ",submit:"ਪ੍ਰਿੰਟ ਰਿਕਵੈਸਟ ਭੇਜੋ",choose:"PDF / JPG / PNG ਚੁਣੋ"},
hi:{title:"प्रिंट सेवा",doc:"दस्तावेज़",upload:"फाइल अपलोड और प्रीव्यू",settings:"प्रिंट सेटिंग",type:"प्रिंट प्रकार",layout:"लेआउट",copies:"कॉपी",sheets:"A4 शीट",total:"कुल",online:"ऑनलाइन",cash:"नकद",submit:"प्रिंट रिक्वेस्ट भेजें",choose:"PDF / JPG / PNG चुनें"},
en:{title:"PRINT SERVICE",doc:"Document",upload:"Upload & Preview",settings:"Print Settings",type:"Print type",layout:"Layout",copies:"Copies",sheets:"A4 sheets",total:"Total",online:"Online",cash:"Cash",submit:"Submit Print Request",choose:"Choose PDF / JPG / PNG"}
};
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;applyLanguage();$("languageScreen").classList.add("hidden");$("orderScreen").classList.remove("hidden")});
function applyLanguage(){const t=T[lang];document.querySelector(".badge").textContent=t.title;document.querySelectorAll(".step")[0].textContent="1. "+t.doc;document.querySelectorAll(".step")[1].textContent="2. "+t.upload;document.querySelectorAll(".step")[2].textContent="3. "+t.settings;document.querySelectorAll(".settings label")[0].childNodes[0].textContent=t.type+" ";document.querySelectorAll(".settings label")[1].childNodes[0].textContent=t.layout+" ";document.querySelectorAll(".settings label")[2].childNodes[0].textContent=t.copies+" ";document.querySelector(".upload").childNodes[0].textContent=t.choose;document.querySelector(".summary div:nth-child(1) span").textContent=t.sheets;document.querySelector(".summary div:nth-child(2) span").textContent=t.total;document.querySelectorAll(".payment label")[0].childNodes[1].textContent=" "+t.online;document.querySelectorAll(".payment label")[1].childNodes[1].textContent=" "+t.cash;document.getElementById("submit").textContent=t.submit}
document.querySelectorAll(".doc").forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.doc;document.querySelectorAll(".doc").forEach(x=>x.style.outline="");b.style.outline="3px solid #e6b84b";calculate()});
$("fileInput").onchange=e=>{files=[...e.target.files];renderPreview();calculate()};
["printType","layout","copies"].forEach(id=>$(id).addEventListener("input",calculate));
function renderPreview(){const box=$("preview");box.innerHTML="";if(!files.length){box.innerHTML="<span>No file selected</span>";return}files.forEach((f,i)=>{const wrap=document.createElement("div");wrap.className="file-preview";const name=document.createElement("small");name.textContent=(i+1)+". "+f.name;wrap.appendChild(name);if(f.type.startsWith("image/")){const img=document.createElement("img");img.src=URL.createObjectURL(f);wrap.appendChild(img)}else if(f.type==="application/pdf"){const frame=document.createElement("iframe");frame.src=URL.createObjectURL(f);wrap.appendChild(frame)}else{wrap.appendChild(document.createTextNode("Preview unavailable"))}box.appendChild(wrap)})}
function calculate(){const copies=Math.max(1,parseInt($("copies").value||1));const layout=$("layout").value;const count=Math.max(1,files.length);let sheets=count*copies;if((layout==="duplex"||selectedDoc==="Aadhaar Card")&&files.length>=2)sheets=Math.ceil(files.length/2)*copies;const rate=sheets<=14?($("printType").value==="bw"?5:10):($("printType").value==="bw"?3:7);$("sheets").textContent=sheets;$("total").textContent="₹"+sheets*rate}
$("submit").onclick=()=>{if(!files.length){alert(lang==="pa"?"ਪਹਿਲਾਂ ਫਾਈਲ ਅੱਪਲੋਡ ਕਰੋ।":lang==="hi"?"पहले फाइल अपलोड करें।":"Please upload your document first.");return}const id="RS-"+requestNo++;const paid=document.querySelector('input[name="payment"]:checked').value==="cash"?"CASH PENDING":"PAID";$("request").textContent="Request ID: "+id+" — "+paid};
